buildscript {
  repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
    maven { url 'https://developer.huawei.com/repo/' }
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:9.1.1'
  }
}

allprojects {
  repositories {
    mavenLocal()
    google()
    maven { url 'https://developer.huawei.com/repo/' }
  }
}

rootProject.buildDir = '../build'
subprojects {
  project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
  project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
  delete rootProject.buildDir
}
