name: moengage_flutter
repository: https://github.com/moengage/Flutter-SDK/

command:
  bootstrap:
    usePubspecOverrides: true
packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*
  - example*
scripts:
  analyze: melos exec -- flutter analyze
  format: melos exec -- dart format .
  get: melos exec -- flutter pub get
  dry-run: flutter pub publish --dry-run
  unittest:
    run: melos exec -- flutter test
    select-package:
      dir-exists:
        - test
      scope: "*interface*"
  update-ios:
    description: Update iOS dependencies
    exec: $MELOS_ROOT_PATH/scripts/update-version.rb
    packageFilters:
      scope: '*_ios'
    env:
      MO_APPLE_VERSIONS: |
        {
          "MoEngagePluginBase": "6.7.0",
          "MoEngagePluginCards": "3.8.0",
          "MoEngagePluginGeofence": "4.7.0",
          "MoEngagePluginInbox": "4.7.0"
        }