name: moengage_flutter_ios
description: iOS implementation of the moengage_flutter plugin
version: 2.2.0
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: moengage_flutter
    platforms:
      ios:
        pluginClass: MoEngageFlutterPlugin
        dartPluginClass: MoEngageFlutterIOS

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  
