# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

def plugin_dev_pods
  test_pluginbase_source = nil
  test_plugincards_source = nil
  test_plugininox_source = nil
  test_plugingeofence_source = nil
  # test_pluginbase_source = { :git => 'https://github.com/moengage/iOS-PluginBase.git', :branch => '' }
  # test_pluginbase_source = { :path => '../../../iOS-PluginBase' }
  # test_plugincards_source = { :path => '../../../apple-plugin-cards' }
  # test_plugininox_source = { :path => '../../../apple-plugin-inbox' }
  # test_plugingeofence_source = { :path => '../../../apple-plugin-geofence' }
  pod 'MoEngagePluginBase', **test_pluginbase_source if test_pluginbase_source
  pod 'MoEngagePluginCards', **test_plugincards_source if test_plugincards_source
  pod 'MoEngagePluginInbox', **test_plugininox_source if test_plugininox_source
  pod 'MoEngagePluginGeofence', **test_plugingeofence_source if test_plugingeofence_source
end

def native_source
  test_source = nil
  # test_source = { :git => 'https://github.com/moengage/MoEngage-iPhone-SDK.git', :branch => '' }
  # test_source = { :path => '../../../MoEngage-iPhone-SDK' }
  return test_source
end

def native_dev_pods
  test_source = native_source
  return unless test_source
  pod 'MoEngage-iOS-SDK', **test_source
  pod 'MoEngageSecurity', **test_source
  pod 'MoEngageCore', **test_source
  pod 'MoEngageMessaging', **test_source
  pod 'MoEngageSDK', **test_source
  pod 'MoEngageTriggerEvaluator', **test_source
  pod 'MoEngageInApps', **test_source
  pod 'MoEngageCards', **test_source
  pod 'MoEngageInbox', **test_source
  pod 'MoEngageGeofence', **test_source
  pod 'MoEngageRichNotification', **test_source
  pod 'MoEngageRealTimeTrigger', **test_source
end

def extension_pods
  test_source = native_source
  if test_source
    pod 'MoEngageRichNotification', **test_source
  else
    pod 'MoEngageRichNotification'
  end
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  native_dev_pods
  plugin_dev_pods

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |configuration|
      configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end

target 'PushTemplates' do
  use_frameworks!
  extension_pods
end

target 'NotificationServices' do
  use_frameworks!
  extension_pods
end
