# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# Uncomment and populate plugin base and native branch for using unreleased pluginbase
# test_native_source = { :git => 'https://github.com/moengage/MoEngage-iPhone-SDK.git', :branch => 'MOEN-37979_ver-upgrade' }

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Uncomment and populate plugin base and native branch for using unreleased pluginbase
  # pod 'MoEngage-iOS-SDK', **test_native_source
  # pod 'MoEngageSecurity', **test_native_source
  # pod 'MoEngageCore', **test_native_source
  # pod 'MoEngageMessaging', **test_native_source
  # pod 'MoEngageSDK', **test_native_source
  # pod 'MoEngageTriggerEvaluator', **test_native_source
  # pod 'MoEngageInApps', **test_native_source
  # pod 'MoEngageCards', **test_native_source
  # pod 'MoEngageInbox', **test_native_source
  # pod 'MoEngageGeofence', **test_native_source
  # pod 'MoEngageRichNotification', **test_native_source
  # pod 'MoEngageRealTimeTrigger', **test_native_source

  # pod 'MoEngagePluginBase', :path => '../../../iOS-PluginBase'
  # pod 'MoEngagePluginCards', :path => '../../../apple-plugin-cards'
  # pod 'MoEngagePluginInbox', :path => '../../../apple-plugin-inbox'
  # pod 'MoEngagePluginGeofence', :path => '../../../apple-plugin-geofence'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |configuration|
      configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end

target 'PushTemplates' do
  use_frameworks!
  pod 'MoEngageRichNotification'
  # pod 'MoEngageRichNotification', **test_native_source
end

target 'NotificationServices' do
  use_frameworks!
  pod 'MoEngageRichNotification'
  # pod 'MoEngageRichNotification', **test_native_source
end
