name: moengage_geofence
description:  Flutter Plugin for using Geofence feature of MoEngage Platform.
version: 7.0.0
homepage: https://www.moengage.com

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.44.0"

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^11.0.0
  moengage_geofence_android: 5.0.0
  moengage_geofence_ios: 5.0.0
  moengage_geofence_platform_interface: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: moengage_geofence_android
      ios:
        default_package: moengage_geofence_ios