name: moengage_personalize
description: Flutter Plugin for using Personalize Experience feature of MoEngage Platform.
version: 0.0.1
homepage: https://www.moengage.com

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moengage_flutter: ^10.0.0
  moengage_personalize_android: 0.0.1
  moengage_personalize_ios: 0.0.1
  moengage_personalize_platform_interface: 0.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: moengage_personalize_android
      ios:
        default_package: moengage_personalize_ios
