name: Verify Pull Request
on:
  workflow_dispatch: # manual trigger
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches: [ "development", "master" ]
jobs:
  verify:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-${{ github.event_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Melos
        run: dart pub global activate melos
      - name: Melos Bootstrap
        run:  melos bootstrap
      - name: Install dependencies
        run: melos get
      - name: Run Dry run
        run: |
          chmod +x ./.github/scripts/dry-run.sh
          ./.github/scripts/dry-run.sh
      - name: Validate Format
        run: |
          chmod +x ./.github/scripts/verify-format.sh
          melos exec -c 1 -- dart format .
          ./.github/scripts/verify-format.sh
      - name: Analyze
        run: melos analyze
      - name: Run tests
        run:  melos unittest
        # We need to build APK before running Ktlint as setting up gradle environment will be handled by flutter build apk
      - name: Flutter build APK
        run: (cd example && flutter build apk)
      - name: Run Ktlint
        run: |
          chmod +x ./.github/scripts/ktlint-verify.sh
          ./.github/scripts/ktlint-verify.sh